name: Docker build

on: [push]

jobs:
  test:
    name: Test the Docker image

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint the Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/386

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Build and push debian
        uses: docker/build-push-action@v4
        with:
          push: false
          platforms: ${{ steps.buildx.outputs.platforms }}

      - name: Build and push alpine
        uses: docker/build-push-action@v4
        with:
          push: false
          platforms: linux/amd64
          file: Dockerfile.alpine
